project
stepancar-web-programming/2022-fall-lab-portfolio-kucher-maksim pull request #2
Opened 2022-11-12 12:44 UTC by maximka65

2022-11-13 23:23 UTC, stepancar commented on blog-ds.html
> +  <link href="css/r esponsive.css" rel="stylesheet">
Видимо responsive сломан

2022-11-13 23:25 UTC, stepancar commented on js/main.js
> +$(document).ready(function() {
Для защиты предлагается переписать этот код без jquery

2022-11-13 23:25 UTC, stepancar commented
Клевый сайт!

2022-11-15 14:57 UTC, maximka65 commented on js/main.js
> +$(document).ready(function() {
я правильно понял, вы имеете ввиду весь файл?

2022-11-22 18:38 UTC, stepancar commented on js/main.js
> +$(document).ready(function() {
@maximka65 да

2022-11-22 18:39 UTC, stepancar commented on js/main.js
> +$(document).ready(function() {
@maximka65 , хотя это будет слишком. Давайте перепишем contactform/contactform.js

2022-11-22 20:26 UTC, maximka65 commented on js/main.js
> +$(document).ready(function() {
я уже переписал 60 процентов функций. Помсмотрите пожалуйста комит

2022-11-22 20:37 UTC, stepancar commented
@maximka65 , не могу проверить ваш PR так как он пока не соответствует ожиданиям. Пожалуйста, отформатируйте код, пофиксите ошибки eslint , stylelint перед отправкой на ревью

2022-11-22 23:10 UTC, maximka65 commented
сделал линтинг

2022-11-22 23:12 UTC, maximka65 commented
так к слову, не смотрите что у меня github пустой, у меня большинство Data science  проектов на gitlab https://gitlab.com/maximka65/ds (вдруг будет интересно)

2022-11-24 05:30 UTC, stepancar commented
@maximka65 , к сожалению, такой ПР посмотреть не могу, так как в изменении 4000 файлов что должно посеять сомнения при написании программы на любом языке

2022-11-24 05:30 UTC, stepancar requested changes
Нужно заигнорить node_modules после чего смогу смотреть

2022-11-24 05:34 UTC, stepancar commented
Я так же советовал бы игнорировал DS_store чтобы он не мозолил глаза в истории

2022-11-24 05:36 UTC, stepancar commented
> так к слову, не смотрите что у меня github пустой, у меня большинство Data science проектов на gitlab https://gitlab.com/maximka65/ds (вдруг будет интересно)

Если что, наличие или отсутствие коммитов на гитхабе не влияет на мое восприятия навыков студента

Но было интересно посмотреть на ваш гит лаб в любом случае, жаль я в этом ничего не понимаю

2022-11-24 07:40 UTC, maximka65 commented
добавил игнорирование лишнего

2022-11-24 21:35 UTC, stepancar commented on .eslintrc.json
> +{
Пожалуйста, форматируйте, проверяйте статическим анализатором, eslint, styleling ваш код перед отправкой на ревью

2022-11-24 21:36 UTC, stepancar requested changes
https://github.com/stepancar-web-programming/2022-fall-lab-portfolio-kucher-maksim/pull/2#discussion_r1031865803

2022-11-25 05:08 UTC, maximka65 commented
переформатировал файлы линтингом

2022-11-25 20:22 UTC, stepancar commented on .gitignore
> +package.json
@maximka65 , package.json критически важен для проекта. Почему вы добавляете его в package.json?

2022-11-25 20:23 UTC, stepancar commented on js/main.js
> +    })
?

2022-11-25 20:25 UTC, stepancar commented on js/.stylelintrc.json
> +{
Это файл конфигурации, не является исходником, а так же stylelintrc не имеет отношения к js, поэтому не ясна причина его расположения в этой дирректории

2022-11-25 20:28 UTC, stepancar commented on js/main.js
> +  }
тут не совсем понятно что происходит так как переменной присвоено одно значение, после, безусловно, другое

2022-11-25 20:33 UTC, stepancar commented on contactform/contactform.js
> +        let ierror = false;
Пытаюсь разобраться в коде. В целом, мне ясна логика, но но названия переменных не совсем описывают суть.
Воспринимайте код, который вы пишете не как разовую работу, а как то, что будет расширяться и поддерживаться.
Предлагаю поработать над понятностью названий

2022-11-25 20:34 UTC, stepancar commented on contactform/contactform.js
> +    if (ferror) return false;
if выражение с телом не перенесенным на след строку ведет к сложности установки дебаггера, так как обычно его можно поставить на конкретную строку

2022-11-26 11:26 UTC, maximka65 commented on contactform/contactform.js
> +        let ierror = false;
я поменял, но какие именно переменные поменять так как rule это переменая содержит правило которое применяется для валидации текста в форме

2022-12-17 03:10 UTC, stepancar commented on package.json
> +    "lint": "npx eslint assets/**/*.js",
не вижу директории assets в этом ПР

2022-12-17 03:12 UTC, stepancar commented on package.json
> +{
не хватает ссылки на demo как просил @KirpaDmitriy

2022-12-17 03:13 UTC, stepancar commented on .vscode/setting.json
> +}
Не принято коммитить настройки IDE, так как IDE  и предпочтения у всех разные

2022-12-17 03:14 UTC, stepancar approved these changes
После исправлений, пожалуйста, смержите ПР

2022-12-28 04:31 UTC, merged